spring:
  thymeleaf:
    cache: false
    encoding: UTF-8 # 개발에서는 캐시 끄기
    prefix: file:src/main/resources/templates/
    # 파일 시스템에서 바로 읽어 개발할 때(핫리로드 체감 ↑):

  output:
    ansi:
      enabled: always            # 컬러 로그

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/aei_dev?useUnicode=true&characterEncoding=utf8mb4
    username: root
    password:
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update           # 개발 편의. 운영에서는 절대 피하세요.
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

server:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB
    encoding:
      charset: UTF-8
      force: true