# application-prod.yml
spring:
  thymeleaf:
    cache: true
    prefix: classpath:/templates/
  datasource:
    url: jdbc:mariadb://${DB_HOST:db}:3306/${DB_NAME:app1_prod}?useUnicode=true&characterEncoding=utf8mb4
    username: ${DB_USER:appuser}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    hibernate.ddl-auto: validate
    show-sql: false
logging.level:
  org.hibernate.SQL: info
  org.hibernate.orm.jdbc.bind: off
